### ISSUE TITLE
Spotify does not return to the initial size

### ISSUE THREAD

**Issue by alizteralvord** [tsmetana/spotify-tray#26] opened 2021-11-03 09:16 UTC
Before minimize to tray
![2021-11-03-160950_1920x1080_scrot](https://user-images.githubusercontent.com/67093484/140034091-67963ae2-5364-436e-91e4-5eb5b766e636.png)

When minimize to tray
![2021-11-03-161002_1920x1080_scrot](https://user-images.githubusercontent.com/67093484/140034118-918e408f-6fd3-44d6-9de3-83eb93011e74.png)

When it appears again it does not return to the initial size ( maximize )
![2021-11-03-161009_1920x1080_scrot](https://user-images.githubusercontent.com/67093484/140034134-7cafadb0-bdaf-4e7c-b81a-cd8077a09450.png)

how to make Spotify back to maximize after minimized to tray ?

**Comment by tsmetana** [comment] 2021-11-12 15:52
This is interesting. I admit I rarely maximize the Spotify client window however on Xfce the window also seems to lose the "maximized" state, however it gets restored to the maximized size so it's almost unnoticeable. I'll see if I can do something about it.

Thanks for the report and sorry for the slow response.

**Comment by alizteralvord** [comment] 2021-11-14 19:28
> This is interesting. I admit I rarely maximize the Spotify client window however on Xfce the window also seems to lose the "maximized" state, however it gets restored to the maximized size so it's almost unnoticeable. I'll see if I can do something about it.
> 
> Thanks for the report and sorry for the slow response.

thanks for the reply.
I have no experience with C language, so all I can do is post this issues

**Comment by tsmetana** [comment] 2021-11-17 11:17
I tried again and I _can't_ reproduce this with Xfwm so it seems to be a problem of the window manager. Could you please check with `xwininfo -wm` whether the restored window still has the same WM hints?

**Comment by alizteralvord** [comment] 2021-11-17 11:38
> I tried again and I _can't_ reproduce this with Xfwm so it seems to be a problem of the window manager. Could you please check with `xwininfo -wm` whether the restored window still has the same WM hints?

the result is like this
2nd one after i restore from tray
![image](https://user-images.githubusercontent.com/67093484/142193260-fb58e943-02a3-436b-a766-0e87e4253bdc.png)

**Comment by tsmetana** [comment] 2021-11-17 21:58
Looks like the window manager removes the WM_STATE property on withdrawal. I think this is not actually incorrect and should be handled by the application. Which window manager and / or desktop environment do you use? I'll try to reproduce and fix this somehow.

**Comment by alizteralvord** [comment] 2021-11-17 23:27
> Looks like the window manager removes the WM_STATE property on withdrawal. I think this is not actually incorrect and should be handled by the application. Which window manager and / or desktop environment do you use? I'll try to reproduce and fix this somehow.

openbox

**Comment by tsmetana** [comment] 2023-01-06 14:23
No idea how to fix this one somewhat simply. The `gdk_window_get_state` doesn't seem to be doing what I'd expect (tell me the window is maximized) and going the pure X protocol way is an overkill. Closing.

**Closed by tsmetana** 2023-01-06 14:23 UTC
